### ISSUE TITLE
ApprovalsApi.post_approval_request_review does not work.

### ISSUE THREAD

**Issue by Satyakakumanu** [launchdarkly/api-client-python#13]
https://github.com/launchdarkly/api-client-python/blob/main/docs/ApprovalsApi.md#post_approval_request_review

I have tested with 10.0.0, also tried generating new tokens with `20220603` version.

```
configuration = launchdarkly_api.Configuration()
configuration.api_key['ApiKey'] = API_KEY

from launchdarkly_api.api import approvals_api
from launchdarkly_api.model.post_approval_request_review_request import PostApprovalRequestReviewRequest

api_client = launchdarkly_api.ApiClient(configuration)
api_instance = approvals_api.ApprovalsApi(api_client)
api_instance.post_approval_request_review()
```

`TypeError: _from_openapi_data() missing 1 required positional argument: 'links'`

**Comment by sloloris** [comment]
Hi @Satyakakumanu,

So sorry about this and that it took so long to get back to you! This turned out to be an error in our API that has been fixed, so you should be able to go ahead and run your code without changing anything and it should work. If you do have any further issues, please feel free to open another issue! I will close this one for now and hope you have a great rest of your week!
